# frozen_string_literal: true

source "https://rubygems.org"

gem 'html_slice'
gem 'stimulux'

gem 'rackr'

gem 'rack-parser'
gem 'zeitwerk'

gem 'puma'
gem 'guard-puma'

gem 'sequel'
gem 'sqlite3'

group :development do
  gem 'rerun'
  gem 'byebug'
  gem 'rspec'
end
