# frozen_string_literal: true

source "https://rubygems.org"

gem "rackr"
gem 'rack-parser'

gem "puma"
gem 'guard-puma'

gem "sequel"
gem "sqlite3"

group :development do
  gem 'byebug'
  gem 'rerun'
end
